language: cpp
compiler:
  - gcc

before_script:
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout tags/0.4.2
  - ./autogen.sh
  - ./configure && make check -j3
  - sudo make install
  - cd ..
  - sudo ldconfig
  - sudo apt-get install libjsoncpp0 libjsoncpp-dev libboost-system-dev libboost-thread-dev lib32ncurses5 lib32ncurses5-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j3

notifications:
  email: false

  irc: 
    channels:
      - "irc.diath.net#lobby"
      - "chat.freenode.net#Toxitty"
    on_success: always
    on_failure: always
