language: cpp
compiler:
  - gcc

before_script:
  # add third party repositories and update apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get -qq update

  # gcc 4.7
  - sudo apt-get -qq install g++-4.7
  - export CXX=g++-4.7
  - export CC=gcc-4.7

  # install libsodium
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout tags/0.4.2
  - ./autogen.sh
  - ./configure
  - sudo make install
  - cd ..
  - sudo ldconfig

  # install other dependencies
  - sudo apt-get install libjsoncpp-dev lib32ncurses5-dev
  - sudo apt-get install libboost-system1.53-dev libboost-thread1.53-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j3

notifications:
  email: false

  irc: 
    channels:
      - "chat.freenode.net#Toxitty"
    on_success: always
    on_failure: always
