language: cpp
compiler:
  - gcc

before_script:
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout tags/0.4.2
  - ./autogen.sh
  - ./configure && make check -j3
  - sudo make install
  - cd ..
  - sudo ldconfig
  - sudo apt-get install libjsoncpp0 libjsoncpp-dev libboost-system1.53-dev libboost-thread1.53-dev lib32ncurses5 lib32ncurses5-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.7
  - export CXX=g++-4.7
  - export CC=gcc-4.7

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j3

notifications:
  email: false

  irc: 
    channels:
      - "irc.diath.net#lobby"
      - "chat.freenode.net#Toxitty"
    on_success: always
    on_failure: always
